version: "3"

vars:
  VERSION: '{{.VERSION | default "latest"}}'
  DOCKERHUB_USER: '{{.DOCKERHUB_USER | default "hestm"}}'
  IMAGE_NAME: "nbf-chat-service"

tasks:
  default:
    cmds:
      - task: run

  run:
    desc: "Run the service"
    cmds:
      - go run ./cmds/main.go
    env:
      CONFIG_PATH: ./config/local.yaml

  docker:
    desc: "Build and push image"
    cmds:
      - docker build -t {{.DOCKERHUB_USER}}/{{.IMAGE_NAME}}:{{.VERSION}} .
      - docker push {{.DOCKERHUB_USER}}/{{.IMAGE_NAME}}:{{.VERSION}}

  docker-multiarch:
    desc: "Build and push multi-arch image"
    cmds:
      - |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t {{.DOCKERHUB_USER}}/{{.IMAGE_NAME}}:{{.VERSION}} \
          --push \
          .
