# This is a sample configuration file for the chat service.
env: dev

grpc:
  host: 0.0.0.0
  port: 50052

user_service:
  address: user_service:50051

group_service:
  address: group_service:50051

postgres_message:
  host: chat-postgres
  port: 5432
  user: postgres
  password: postgres
  db_name: chat

redpanda:
  brokers:
    - redpanda:9092
  group_id: chat-service
  topics:
    - matcher.group.accept
    - matcher.group.leave
    - matcher.group.kick
