# This is a sample configuration file for the chat service.
env: dev

grpc:
  host: 0.0.0.0
  port: 50052

user_service:
  host: user_service
  port: 60001

group_service:
  host: matcher_service
  port: 50051

postgres_message:
  host: chat-postgres
  port: 5432
  user: postgres
  password: postgres
  db_name: chat
