# This is a sample configuration file for the chat service.
env: dev

grpc:
  host: 0.0.0.0
  port: 50052

user_service:
  address: localhost:60001

group_service:
  address: localhost:60002

postgres_message:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db_name: chat
